server:
  port: 8081
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    discovery-client-enabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&useInformationSchema=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

config:
  appName: 123
  env: dev